language: node_js
node_js:
  - 11

addons:
  chrome: stable

before_script:
  - npm install
  
script:
  - npm run test
  - npm run wdio

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dirt: build
  on:
    branch: master
    